# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1148, 804)
        self.feed = QLabel(Form)
        self.feed.setObjectName(u"feed")
        self.feed.setGeometry(QRect(20, 10, 870, 760))
        self.feed.setFrameShape(QFrame.Box)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(910, 10, 231, 751))
        self.EmpID_3 = QLabel(self.groupBox)
        self.EmpID_3.setObjectName(u"EmpID_3")
        self.EmpID_3.setGeometry(QRect(150, 320, 47, 13))
        self.EmpID_2 = QLabel(self.groupBox)
        self.EmpID_2.setObjectName(u"EmpID_2")
        self.EmpID_2.setGeometry(QRect(150, 200, 47, 13))
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 120, 211, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.EmpID_5 = QLabel(self.groupBox)
        self.EmpID_5.setObjectName(u"EmpID_5")
        self.EmpID_5.setGeometry(QRect(150, 560, 47, 13))
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 470, 211, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.EmpPhoto_3 = QLabel(self.groupBox)
        self.EmpPhoto_3.setObjectName(u"EmpPhoto_3")
        self.EmpPhoto_3.setGeometry(QRect(40, 260, 81, 91))
        self.EmpPhoto_3.setAutoFillBackground(False)
        self.EmpPhoto_3.setFrameShape(QFrame.Box)
        self.EmpPhoto_2 = QLabel(self.groupBox)
        self.EmpPhoto_2.setObjectName(u"EmpPhoto_2")
        self.EmpPhoto_2.setGeometry(QRect(40, 140, 81, 91))
        self.EmpPhoto_2.setAutoFillBackground(False)
        self.EmpPhoto_2.setFrameShape(QFrame.Box)
        self.EmpName_2 = QLabel(self.groupBox)
        self.EmpName_2.setObjectName(u"EmpName_2")
        self.EmpName_2.setGeometry(QRect(150, 170, 47, 13))
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 360, 211, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.EmpID_4 = QLabel(self.groupBox)
        self.EmpID_4.setObjectName(u"EmpID_4")
        self.EmpID_4.setGeometry(QRect(150, 440, 47, 13))
        self.EmpID_6 = QLabel(self.groupBox)
        self.EmpID_6.setObjectName(u"EmpID_6")
        self.EmpID_6.setGeometry(QRect(150, 680, 47, 13))
        self.EmpID = QLabel(self.groupBox)
        self.EmpID.setObjectName(u"EmpID")
        self.EmpID.setGeometry(QRect(150, 80, 47, 13))
        self.EmpName_5 = QLabel(self.groupBox)
        self.EmpName_5.setObjectName(u"EmpName_5")
        self.EmpName_5.setGeometry(QRect(150, 530, 47, 13))
        self.line_5 = QFrame(self.groupBox)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(20, 600, 211, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.EmpName_6 = QLabel(self.groupBox)
        self.EmpName_6.setObjectName(u"EmpName_6")
        self.EmpName_6.setGeometry(QRect(150, 650, 47, 13))
        self.line_6 = QFrame(self.groupBox)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(20, 710, 211, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.EmpName_4 = QLabel(self.groupBox)
        self.EmpName_4.setObjectName(u"EmpName_4")
        self.EmpName_4.setGeometry(QRect(150, 410, 47, 13))
        self.EmpPhoto_5 = QLabel(self.groupBox)
        self.EmpPhoto_5.setObjectName(u"EmpPhoto_5")
        self.EmpPhoto_5.setGeometry(QRect(40, 500, 81, 91))
        self.EmpPhoto_5.setAutoFillBackground(False)
        self.EmpPhoto_5.setFrameShape(QFrame.Box)
        self.EmpName_3 = QLabel(self.groupBox)
        self.EmpName_3.setObjectName(u"EmpName_3")
        self.EmpName_3.setGeometry(QRect(150, 290, 47, 13))
        self.EmpName = QLabel(self.groupBox)
        self.EmpName.setObjectName(u"EmpName")
        self.EmpName.setGeometry(QRect(150, 50, 47, 13))
        self.EmpPhoto_6 = QLabel(self.groupBox)
        self.EmpPhoto_6.setObjectName(u"EmpPhoto_6")
        self.EmpPhoto_6.setGeometry(QRect(40, 620, 81, 91))
        self.EmpPhoto_6.setAutoFillBackground(False)
        self.EmpPhoto_6.setFrameShape(QFrame.Box)
        self.EmpPhoto = QLabel(self.groupBox)
        self.EmpPhoto.setObjectName(u"EmpPhoto")
        self.EmpPhoto.setGeometry(QRect(40, 20, 81, 91))
        self.EmpPhoto.setAutoFillBackground(False)
        self.EmpPhoto.setFrameShape(QFrame.Box)
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 230, 211, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.EmpPhoto_4 = QLabel(self.groupBox)
        self.EmpPhoto_4.setObjectName(u"EmpPhoto_4")
        self.EmpPhoto_4.setGeometry(QRect(40, 380, 81, 91))
        self.EmpPhoto_4.setAutoFillBackground(False)
        self.EmpPhoto_4.setFrameShape(QFrame.Box)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.feed.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"Attendance Record", None))
        self.EmpID_3.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpID_2.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpID_5.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpPhoto_3.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
        self.EmpPhoto_2.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
        self.EmpName_2.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpID_4.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpID_6.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpID.setText(QCoreApplication.translate("Form", u"EmpID", None))
        self.EmpName_5.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpName_6.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpName_4.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpPhoto_5.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
        self.EmpName_3.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpName.setText(QCoreApplication.translate("Form", u"EmpName", None))
        self.EmpPhoto_6.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
        self.EmpPhoto.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
        self.EmpPhoto_4.setText(QCoreApplication.translate("Form", u"EmpPhoto", None))
    # retranslateUi

